#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'CST455_Final_HPS' in
 * file '../CST455_Final_HPS.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'FibonacciSeq_0', class 'FibonacciSeq'
 * The macros are prefixed with 'FIBONACCISEQ_0_'.
 * The prefix is the slave descriptor.
 */
#define FIBONACCISEQ_0_COMPONENT_TYPE FibonacciSeq
#define FIBONACCISEQ_0_COMPONENT_NAME FibonacciSeq_0
#define FIBONACCISEQ_0_BASE 0x0
#define FIBONACCISEQ_0_SPAN 16
#define FIBONACCISEQ_0_END 0xf

/*
 * Macros for device 'Pushbuttons_0', class 'Pushbuttons'
 * The macros are prefixed with 'PUSHBUTTONS_0_'.
 * The prefix is the slave descriptor.
 */
#define PUSHBUTTONS_0_COMPONENT_TYPE Pushbuttons
#define PUSHBUTTONS_0_COMPONENT_NAME Pushbuttons_0
#define PUSHBUTTONS_0_BASE 0x10
#define PUSHBUTTONS_0_SPAN 16
#define PUSHBUTTONS_0_END 0x1f

/*
 * Macros for device 'Switches_0', class 'Switches'
 * The macros are prefixed with 'SWITCHES_0_'.
 * The prefix is the slave descriptor.
 */
#define SWITCHES_0_COMPONENT_TYPE Switches
#define SWITCHES_0_COMPONENT_NAME Switches_0
#define SWITCHES_0_BASE 0x20
#define SWITCHES_0_SPAN 16
#define SWITCHES_0_END 0x2f

/*
 * Macros for device 'LEDs_0', class 'LEDs'
 * The macros are prefixed with 'LEDS_0_'.
 * The prefix is the slave descriptor.
 */
#define LEDS_0_COMPONENT_TYPE LEDs
#define LEDS_0_COMPONENT_NAME LEDs_0
#define LEDS_0_BASE 0x30
#define LEDS_0_SPAN 16
#define LEDS_0_END 0x3f

/*
 * Macros for device 'HEX01', class 'SevenSegDecoder'
 * The macros are prefixed with 'HEX01_'.
 * The prefix is the slave descriptor.
 */
#define HEX01_COMPONENT_TYPE SevenSegDecoder
#define HEX01_COMPONENT_NAME HEX01
#define HEX01_BASE 0x40
#define HEX01_SPAN 16
#define HEX01_END 0x4f

/*
 * Macros for device 'HEX23', class 'SevenSegDecoder'
 * The macros are prefixed with 'HEX23_'.
 * The prefix is the slave descriptor.
 */
#define HEX23_COMPONENT_TYPE SevenSegDecoder
#define HEX23_COMPONENT_NAME HEX23
#define HEX23_BASE 0x50
#define HEX23_SPAN 16
#define HEX23_END 0x5f

/*
 * Macros for device 'HEX45', class 'SevenSegDecoder'
 * The macros are prefixed with 'HEX45_'.
 * The prefix is the slave descriptor.
 */
#define HEX45_COMPONENT_TYPE SevenSegDecoder
#define HEX45_COMPONENT_NAME HEX45
#define HEX45_BASE 0x60
#define HEX45_SPAN 16
#define HEX45_END 0x6f


#endif /* _ALTERA_HPS_0_H_ */
