#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'TermProject' in
 * file '../TermProject.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'CRC_0', class 'CRC'
 * The macros are prefixed with 'CRC_0_'.
 * The prefix is the slave descriptor.
 */
#define CRC_0_COMPONENT_TYPE CRC
#define CRC_0_COMPONENT_NAME CRC_0
#define CRC_0_BASE 0x0
#define CRC_0_SPAN 16
#define CRC_0_END 0xf

/*
 * Macros for device 'SevenSegDecoder_5', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_5_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_5_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_5_COMPONENT_NAME SevenSegDecoder_5
#define SEVENSEGDECODER_5_BASE 0x10
#define SEVENSEGDECODER_5_SPAN 16
#define SEVENSEGDECODER_5_END 0x1f

/*
 * Macros for device 'SevenSegDecoder_0', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_0_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_0_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_0_COMPONENT_NAME SevenSegDecoder_0
#define SEVENSEGDECODER_0_BASE 0x20
#define SEVENSEGDECODER_0_SPAN 16
#define SEVENSEGDECODER_0_END 0x2f

/*
 * Macros for device 'SevenSegDecoder_1', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_1_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_1_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_1_COMPONENT_NAME SevenSegDecoder_1
#define SEVENSEGDECODER_1_BASE 0x30
#define SEVENSEGDECODER_1_SPAN 16
#define SEVENSEGDECODER_1_END 0x3f

/*
 * Macros for device 'SevenSegDecoder_2', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_2_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_2_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_2_COMPONENT_NAME SevenSegDecoder_2
#define SEVENSEGDECODER_2_BASE 0x40
#define SEVENSEGDECODER_2_SPAN 16
#define SEVENSEGDECODER_2_END 0x4f

/*
 * Macros for device 'SevenSegDecoder_3', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_3_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_3_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_3_COMPONENT_NAME SevenSegDecoder_3
#define SEVENSEGDECODER_3_BASE 0x50
#define SEVENSEGDECODER_3_SPAN 16
#define SEVENSEGDECODER_3_END 0x5f

/*
 * Macros for device 'SevenSegDecoder_4', class 'SevenSegDecoder'
 * The macros are prefixed with 'SEVENSEGDECODER_4_'.
 * The prefix is the slave descriptor.
 */
#define SEVENSEGDECODER_4_COMPONENT_TYPE SevenSegDecoder
#define SEVENSEGDECODER_4_COMPONENT_NAME SevenSegDecoder_4
#define SEVENSEGDECODER_4_BASE 0x60
#define SEVENSEGDECODER_4_SPAN 16
#define SEVENSEGDECODER_4_END 0x6f

/*
 * Macros for device 'UART_RX_0', class 'UART_RX'
 * The macros are prefixed with 'UART_RX_0_'.
 * The prefix is the slave descriptor.
 */
#define UART_RX_0_COMPONENT_TYPE UART_RX
#define UART_RX_0_COMPONENT_NAME UART_RX_0
#define UART_RX_0_BASE 0x70
#define UART_RX_0_SPAN 16
#define UART_RX_0_END 0x7f

/*
 * Macros for device 'ClockDivider_0', class 'ClockDivider'
 * The macros are prefixed with 'CLOCKDIVIDER_0_'.
 * The prefix is the slave descriptor.
 */
#define CLOCKDIVIDER_0_COMPONENT_TYPE ClockDivider
#define CLOCKDIVIDER_0_COMPONENT_NAME ClockDivider_0
#define CLOCKDIVIDER_0_BASE 0x80
#define CLOCKDIVIDER_0_SPAN 16
#define CLOCKDIVIDER_0_END 0x8f


#endif /* _ALTERA_HPS_0_H_ */
